# Generated by Django 3.2.20 on 2023-08-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=250)),
                ('posted', models.DateField()),
                ('courseimage', models.ImageField(default='', upload_to='pics/')),
                ('category', models.TextField()),
            ],
        ),
    ]
